version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn --version
      - echo Installing Docker...
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - echo Installing buildx component...
      - mkdir -p ~/.docker/cli-plugins
      - curl -L https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod a+x ~/.docker/cli-plugins/docker-buildx
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 018370195085.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean install
      - echo Building the Docker image with BuildKit...
      - docker buildx create --use --name mybuilder
      - docker buildx build --builder mybuilder --platform linux/amd64 -t orders .
      - docker tag orders:latest 018370195085.dkr.ecr.us-east-1.amazonaws.com/orders:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 018370195085.dkr.ecr.us-east-1.amazonaws.com/orders:latest

